[package]
name = "whost"
version = "0.1.7"
edition = "2021"

[dependencies]
tokio = { version = "1.52", features = ["full", "rt", "macros"] }
wasmtime = { version = "43.0.0", features = ["component-model", "async", "pooling-allocator"] }
wasmtime-wasi = "43.0.0"
wasmtime-wasi-http = "43.0.0"
wit-bindgen = { version = "0.56.0", features = ["async"] }
