[package]
name = "whost"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
reqwest = "0.13.5"
tokio = { version = "1.53.2", features = ["full"] }
url = "2.5.8"
wasmtime = { version = "49.0.2", features = ["component-model", "component-model-async", "async"] }
wasmtime-wasi = "49.0.2"
wit-bindgen = { version = "0.62.0", features = ["async"] }
