package mycustomwasm:demo;

interface dictionary-ops {
    dict-get: func(key: string) -> option<string>;
    dict-set: func(key: string, value: string);
}

interface http {
    get: async func(url: string) -> result<string, string>;
}

world mycustomwasm-world {
    import dictionary-ops;
    import http;
    export webpageinspector: async func(url: string);
}
